name: "Populate cachix"
on:
  push:
jobs:
  agda-version:
    continue-on-error: true
    strategy:
      matrix:
        version: [2_6_1, 2_6_2, 2_6_3, 2_6_4, 2_7_0, 2_8_0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: all-agda
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#agdaPackages-${{ matrix.version }}.all --print-build-logs
