name: "Populate"
on:
  push:
jobs:
  population:
    strategy:
      matrix:
        version: [2.6.1, 2.6.2, 2.6.3, 2.6.4, rc]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: all-agda
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#agdaPackages-${{ matrix.version }}.all --print-build-logs
